# -*- coding: utf-8 -*-
"""fault_model_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hnWzcgBeNxyylxabb8MWqMbprRM7kCg3
"""

import itertools
import pandas as pd

circuit_defs_2 = [
    ("AND",   lambda a, b: a & b),
    ("OR",    lambda a, b: a | b),
    ("NAND",  lambda a, b: ~(a & b) & 1),
    ("NOR",   lambda a, b: ~(a | b) & 1),
    ("XOR",   lambda a, b: a ^ b),
    ("XNOR",  lambda a, b: ~(a ^ b) & 1),
    ("IMPL",  lambda a, b: (~a | b) & 1),
    ("BUF",   lambda a, b: a),
    ("NOT",   lambda a, b: (~a) & 1),
    ("COMP",  lambda a, b: int(a == b)),
]
circuit_defs_3 = [
    ("AND3",    lambda a, b, c: (a & b & c, [])),
    ("OR3",     lambda a, b, c: (a | b | c, [])),
    ("NAND3",   lambda a, b, c: ((~(a & b & c)) & 1, [])),
    ("NOR3",    lambda a, b, c: ((~(a | b | c)) & 1, [])),
    ("XOR3",    lambda a, b, c: (a ^ b ^ c, [])),
    ("XNOR3",   lambda a, b, c: ((~(a ^ b ^ c)) & 1, [])),
    ("MAJ",     lambda a, b, c: (int((a+b+c)>=2), [])),
    ("PARITY",  lambda a, b, c: ((a+b+c)%2, [])),
    ("COMP3",   lambda a, b, c: (int(a==b==c), [])),
    ("ADD_OR",  lambda a, b, c: ((a | b) | c, [("a_or_b", a | b)])),
    ("ADD_AND", lambda a, b, c: ((a & b) & c, [("a_and_b", a & b)])),
    ("MIXED1",  lambda a, b, c: (((a ^ b) & c), [("a_xor_b", a ^ b)])),
    ("MIXED2",  lambda a, b, c: (((a & c) | b), [("a_and_c", a & c)])),
]

fault_types = [0, 1, 2]

def inject_fault(val, fault_type, bridge_target=None):
    if fault_type == 0:
        return 0
    elif fault_type == 1:
        return 1
    elif fault_type == 2 and bridge_target is not None:
        return bridge_target
    else:
        return val

records = []

for idx, (name, func) in enumerate(circuit_defs_2):
    for a, b in itertools.product([0, 1], repeat=2):
        fault_free = func(a, b)
        for sig, bridge_targets in [
            ('a', [b]),
            ('b', [a]),
            ('output', [])]:
            for ftype in fault_types:
                if sig == 'a':
                    fa = inject_fault(a, ftype, bridge_targets[0])
                    fb = b
                elif sig == 'b':
                    fa = a
                    fb = inject_fault(b, ftype, bridge_targets[0])
                else:
                    fa, fb = a, b
                faulty = func(fa, fb)
                records.append({
                    'inputs': (a, b, 0),
                    'n_inputs': 2,
                    'circuit_family': 'LOGIC',
                    'circuit_id': idx,
                    'circuit_type': name,
                    'fault_signal': sig,
                    'fault_type': ftype,
                    'fault_free_output': int(fault_free),
                    'fault_output': int(faulty),
                    'intermediate_outputs': {},
                })

for idx, (name, func) in enumerate(circuit_defs_3):
    for a, b, c in itertools.product([0, 1], repeat=3):
        fault_free, intermediates = func(a, b, c)
        interm_dict = dict(intermediates)
        for sig, bridge_targets in [
            ('a', [b, c]),
            ('b', [a, c]),
            ('c', [a, b]),
            ('output', [])]:
            for ftype in fault_types:
                if sig == 'a':
                    fa = inject_fault(a, ftype, bridge_targets[0])
                    fb = b
                    fc = c
                elif sig == 'b':
                    fa = a
                    fb = inject_fault(b, ftype, bridge_targets[0])
                    fc = c
                elif sig == 'c':
                    fa = a
                    fb = b
                    fc = inject_fault(c, ftype, bridge_targets[0])
                else:
                    fa, fb, fc = a, b, c
                out_res, interm = func(fa, fb, fc)
                records.append({
                    'inputs': (a, b, c),
                    'n_inputs': 3,
                    'circuit_family': 'LOGIC',
                    'circuit_id': idx,
                    'circuit_type': name,
                    'fault_signal': sig,
                    'fault_type': ftype,
                    'fault_free_output': int(fault_free),
                    'fault_output': int(out_res),
                    'intermediate_outputs': dict(intermediates),
                })
        for k, v in interm_dict.items():
            for ftype in fault_types:
                if name == "ADD_OR":
                    wrong_v = inject_fault(v, ftype, None)
                    final_out = wrong_v | c
                elif name == "ADD_AND":
                    wrong_v = inject_fault(v, ftype, None)
                    final_out = wrong_v & c
                elif name == "MIXED1":
                    wrong_v = inject_fault(v, ftype, None)
                    final_out = wrong_v & c
                elif name == "MIXED2":
                    wrong_v = inject_fault(v, ftype, None)
                    final_out = wrong_v | b
                else:
                    continue
                records.append({
                    'inputs': (a, b, c),
                    'n_inputs': 3,
                    'circuit_family': 'LOGIC',
                    'circuit_id': idx,
                    'circuit_type': name,
                    'fault_signal': f'intermediate_{k}',
                    'fault_type': ftype,
                    'fault_free_output': int(fault_free),
                    'fault_output': int(final_out),
                    'intermediate_outputs': interm_dict
                })

df_raw = pd.DataFrame(records)
feature_cols = ['inputs','fault_signal','circuit_type','n_inputs','circuit_family','intermediate_outputs']
uniq_keys = df_raw[['inputs','fault_signal','circuit_type','fault_output']].astype(str).agg('|'.join, axis=1)
df_raw['ambiguous_type'] = uniq_keys.duplicated(keep=False)

print(f"Dataset prepared. Total samples: {len(df_raw)}; Ambiguous type labelings: {df_raw['ambiguous_type'].sum()}")

df_raw

import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler, PolynomialFeatures
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.ensemble import RandomForestClassifier
import xgboost as xgb
from imblearn.over_sampling import SMOTE
import matplotlib.pyplot as plt
import seaborn as sns

df = df_raw.copy()
input_cols = ['in_a','in_b','in_c']
df[input_cols] = pd.DataFrame(df['inputs'].tolist(), index=df.index)
possible_inters = ['a_or_b','a_and_b','a_xor_b','a_and_c']
for key in possible_inters:
    df[f'inter_{key}'] = df['intermediate_outputs'].apply(lambda d: d.get(key,0) if isinstance(d,dict) else 0)
ckt_ohe = pd.get_dummies(df['circuit_type'], prefix='ckt')

feature_cols_final = input_cols + [
    'fault_free_output','fault_output','n_inputs',
    'inter_a_or_b','inter_a_and_b','inter_a_xor_b','inter_a_and_c'
] + list(ckt_ohe.columns)
X_full = pd.concat([df[feature_cols_final[:-len(ckt_ohe.columns)]], ckt_ohe], axis=1).astype(np.float32).values

df_type = df[~df['ambiguous_type']]
X_type = X_full[~df['ambiguous_type']]
le_type = LabelEncoder()
y_type = le_type.fit_transform(df_type['fault_type'])
smote = SMOTE(random_state=42)
X_type_res, y_type_res = smote.fit_resample(X_type, y_type)
X_train, X_test, y_train, y_test = train_test_split(X_type_res, y_type_res, test_size=0.3, stratify=y_type_res, random_state=42)

rf = RandomForestClassifier(n_estimators=400, max_depth=None, class_weight='balanced', random_state=42)
rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)
print("\nRandom Forest (type, non-ambiguous) Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred, target_names=[str(x) for x in le_type.classes_]))
cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(8,6))
sns.heatmap(cm, annot=True, fmt='d')
plt.title("RF Fault Type Confusion Matrix (unambiguous)")
plt.show()


le_loc = LabelEncoder()
y_loc = le_loc.fit_transform(df['fault_signal'])
X_loc_res, y_loc_res = smote.fit_resample(X_full, y_loc)
X_train_l, X_test_l, y_train_l, y_test_l = train_test_split(X_loc_res, y_loc_res, test_size=0.3, stratify=y_loc_res, random_state=42)
rf_l = RandomForestClassifier(n_estimators=400, max_depth=None, class_weight='balanced', random_state=42)
rf_l.fit(X_train_l, y_train_l)
y_pred_l = rf_l.predict(X_test_l)
print("\nRandom Forest (location, all) Accuracy:", accuracy_score(y_test_l, y_pred_l))
print(classification_report(y_test_l, y_pred_l, target_names=le_loc.classes_))
cm_l = confusion_matrix(y_test_l, y_pred_l)
plt.figure(figsize=(10,7))
sns.heatmap(cm_l, annot=True, fmt='d')
plt.title("RF Fault Location Confusion Matrix")
plt.show()

import pandas as pd
import numpy as np
from collections import Counter

circuit_rows = []

for name, func in circuit_defs_2:
    circuit_rows.append({
        "circuit_type": name,
        "#inputs": 2,
        "has_intermediate": "N",
        "logical_expression": name
    })


structured_with_inter = {"ADD_OR", "ADD_AND", "MIXED1", "MIXED2"}

for name, func in circuit_defs_3:
    has_inter = "Y" if name in structured_with_inter else "N"
    circuit_rows.append({
        "circuit_type": name,
        "#inputs": 3,
        "has_intermediate": has_inter,
        "logical_expression": name  # again, you can refine later
    })

table1 = pd.DataFrame(circuit_rows)
print("TABLE 1 – Circuit library summary")
display(table1)


print(table1.to_latex(index=False, caption="Circuit library summary", label="tab:circuit_lib"))



n_total = len(df_raw)
n_circuits = df_raw['circuit_type'].nunique()
n_fault_types = df_raw['fault_type'].nunique()
n_locations = df_raw['fault_signal'].nunique()
n_ambig = df_raw['ambiguous_type'].sum()
n_unambig = n_total - n_ambig

stats_rows = [
    {"Metric": "Number of circuits", "Value": n_circuits},
    {"Metric": "Total samples", "Value": n_total},
    {"Metric": "Number of fault types", "Value": n_fault_types},
    {"Metric": "Number of fault locations", "Value": n_locations},
    {"Metric": "Ambiguous samples", "Value": int(n_ambig)},
    {"Metric": "Unambiguous samples", "Value": int(n_unambig)},
]

table2 = pd.DataFrame(stats_rows)
print("\nTABLE 2 – Dataset statistics")
display(table2)
print(table2.to_latex(index=False, caption="Dataset statistics", label="tab:dataset_stats"))


rf_params = {
    "n_estimators": getattr(rf_type, "n_estimators", "–"),
    "max_depth": getattr(rf_type, "max_depth", "–"),
    "class_weight": getattr(rf_type, "class_weight", "–"),
}


xgb_params = {
    "n_estimators": getattr(xgb_type, "n_estimators", "–"),
    "max_depth": getattr(xgb_type, "max_depth", "–"),
    "learning_rate": getattr(xgb_type, "learning_rate", "–"),
}


mlp_params = {
    "layers": "256-128 (ReLU)",
    "batch_norm": "Yes",
    "dropout": "0.3 / 0.2",
    "optimizer": "Adam",
    "epochs": 60
}

hyper_rows = [
    {"Model": "Random Forest", "Key": "n_estimators", "Value": rf_params["n_estimators"]},
    {"Model": "Random Forest", "Key": "max_depth", "Value": rf_params["max_depth"]},
    {"Model": "Random Forest", "Key": "class_weight", "Value": rf_params["class_weight"]},

    {"Model": "XGBoost", "Key": "n_estimators", "Value": xgb_params["n_estimators"]},
    {"Model": "XGBoost", "Key": "max_depth", "Value": xgb_params["max_depth"]},
    {"Model": "XGBoost", "Key": "learning_rate", "Value": xgb_params["learning_rate"]},

    {"Model": "MLP", "Key": "layers", "Value": mlp_params["layers"]},
    {"Model": "MLP", "Key": "batch_norm", "Value": mlp_params["batch_norm"]},
    {"Model": "MLP", "Key": "dropout", "Value": mlp_params["dropout"]},
    {"Model": "MLP", "Key": "optimizer", "Value": mlp_params["optimizer"]},
    {"Model": "MLP", "Key": "epochs", "Value": mlp_params["epochs"]},
]

table3 = pd.DataFrame(hyper_rows)
print("\nTABLE 3 – Model hyperparameters")
display(table3)
print(table3.to_latex(index=False, caption="Model hyperparameters", label="tab:model_hparams"))

import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler, PolynomialFeatures
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.ensemble import RandomForestClassifier
import xgboost as xgb
from imblearn.over_sampling import SMOTE
import matplotlib.pyplot as plt
import seaborn as sns

df = df_raw.copy()
input_cols = ['in_a','in_b','in_c']
df[input_cols] = pd.DataFrame(df['inputs'].tolist(), index=df.index)
possible_inters = ['a_or_b','a_and_b','a_xor_b','a_and_c']
for key in possible_inters:
    df[f'inter_{key}'] = df['intermediate_outputs'].apply(lambda d: d.get(key,0) if isinstance(d,dict) else 0)
ckt_ohe = pd.get_dummies(df['circuit_type'], prefix='ckt')

# Features
feature_cols_final = input_cols + [
    'fault_free_output','fault_output','n_inputs',
    'inter_a_or_b','inter_a_and_b','inter_a_xor_b','inter_a_and_c'
] + list(ckt_ohe.columns)
X_full = pd.concat([df[feature_cols_final[:-len(ckt_ohe.columns)]], ckt_ohe], axis=1).astype(np.float32).values

# 1. Fault Type Model (Unambiguous)
df_type = df[~df['ambiguous_type']]
X_type = X_full[~df['ambiguous_type']]
le_type = LabelEncoder()
y_type = le_type.fit_transform(df_type['fault_type'])
smote = SMOTE(random_state=42)
X_type_res, y_type_res = smote.fit_resample(X_type, y_type)
X_train, X_test, y_train, y_test = train_test_split(X_type_res, y_type_res, test_size=0.3, stratify=y_type_res, random_state=42)

rf = RandomForestClassifier(n_estimators=400, max_depth=None, class_weight='balanced', random_state=42)
rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)
print("\nRandom Forest (type, non-ambiguous) Accuracy:", accuracy_score(y_test, y_pred))

cm = confusion_matrix(y_test, y_pred)

sns.set_theme(style="whitegrid", font_scale=1.2)
plt.figure(figsize=(8, 6), dpi=300)

sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=[str(x) for x in le_type.classes_],
            yticklabels=[str(x) for x in le_type.classes_],
            annot_kws={"size": 16, "weight": "bold"},
            cbar_kws={'label': 'Number of Samples'},
            linewidths=1, linecolor='black')

plt.title("RF Fault Type Confusion Matrix (Unambiguous)", fontsize=16, fontweight='bold', pad=15)
plt.ylabel('True Fault Type', fontsize=14, fontweight='bold')
plt.xlabel('Predicted Fault Type', fontsize=14, fontweight='bold')
plt.xticks(rotation=0)
plt.yticks(rotation=0)
plt.tight_layout()

plt.savefig("final_type_high_res.png", format='png', dpi=300, bbox_inches='tight')
plt.show()

# 2. Fault Location Model (All Data)
le_loc = LabelEncoder()
y_loc = le_loc.fit_transform(df['fault_signal'])
X_loc_res, y_loc_res = smote.fit_resample(X_full, y_loc)
X_train_l, X_test_l, y_train_l, y_test_l = train_test_split(X_loc_res, y_loc_res, test_size=0.3, stratify=y_loc_res, random_state=42)

rf_l = RandomForestClassifier(n_estimators=400, max_depth=None, class_weight='balanced', random_state=42)
rf_l.fit(X_train_l, y_train_l)
y_pred_l = rf_l.predict(X_test_l)
print("\nRandom Forest (location, all) Accuracy:", accuracy_score(y_test_l, y_pred_l))


cm_l = confusion_matrix(y_test_l, y_pred_l)

plt.figure(figsize=(10, 8), dpi=300)
sns.heatmap(cm_l, annot=True, fmt='d', cmap='Blues',
            xticklabels=le_loc.classes_,
            yticklabels=le_loc.classes_,
            annot_kws={"size": 12, "weight": "bold"},
            cbar_kws={'label': 'Number of Samples'},
            linewidths=0.5, linecolor='gray')

plt.title("RF Fault Location Confusion Matrix", fontsize=16, fontweight='bold', pad=15)
plt.ylabel('True Fault Location', fontsize=14, fontweight='bold')
plt.xlabel('Predicted Fault Location', fontsize=14, fontweight='bold')

plt.xticks(rotation=45, ha='right', fontsize=11, fontweight='bold')
plt.yticks(rotation=0, fontsize=11, fontweight='bold')
plt.tight_layout()

plt.savefig("final_loc_high_res.png", format='png', dpi=300, bbox_inches='tight')
plt.show()

